const assert = require("assert");
const fs = require("fs");
const path = require("path");

const read = (relative) => fs.readFileSync(path.resolve(__dirname, "..", relative), "utf8");
const schema = read("prisma/schema.prisma");
const migration = read("prisma/migrations/20260823230000_add_designation_level_leave_ledger/migration.sql");
const levels = read("src/services/designationEmploymentLevelService.js");
const provisioning = read("src/services/leaveEntitlementProvisioningService.js");
const ledger = read("src/services/employeeLeaveLedgerService.js");
const balance = read("src/services/leaveBalanceService.js");
const leaveRoutes = read("src/routes/leaveRoutes.js");
const employeeRoutes = read("src/routes/employeeRoutes.js");
const onboardingRoutes = read("src/routes/onboardingRoutes.js");
const entitlementsPage = read("../src/pages/LeaveEntitlements.jsx");
const requestPage = read("../src/pages/LeaveRequests.jsx");
const profilePanel = read("../src/components/leave/EmployeeLeaveProfilePanel.jsx");
const diagnosticScript = read("scripts/diagnoseBaselineLeavePolicyConflicts.js");
const previewScript = read("scripts/previewCurrentEmployeeLeaveReconciliation.js");
const normalizationProposal = read("scripts/proposeAnnualLeavePolicyNormalization.js");
const baselineReconciliation = read("src/services/baselineLeaveEntitlementReconciliationService.js");
const baselineReconciliationPreview = read("scripts/preview2026BaselineLeaveEntitlementReconciliation.js");
const baselineReconciliationApply = read("scripts/apply2026BaselineLeaveEntitlementReconciliation.js");
const directory = read("../src/components/employees/EmployeeTable.jsx");
const employeeProfile = read("../src/components/employees/EmployeeProfile.jsx");
const onboarding = read("../src/pages/EmployeeOnboarding.jsx");
const designations = read("../src/pages/Designations.jsx");
const legacyLeave = read("../src/pages/LeaveManagement.jsx");
const staleRoutes = read("../src/routes/AppRoutes.jsx");

assert.match(schema, /model OrganizationEmploymentLevel/);
assert.match(schema, /Designation\.careerLevel remains the authoritative employee-level mapping/);
assert.match(schema, /model LeaveEntitlementMatrixRule/);
assert.match(schema, /model LeaveEntitlementAllocation/);
assert.doesNotMatch(schema, /model EmployeeEmploymentLevel/);
assert.match(migration, /INSERT INTO "organization_employment_levels"/);
assert.match(migration, /leave_entitlement_allocations/);
assert.match(migration, /leave_policies_organizationId_id_key/);

assert.match(levels, /designation\.careerLevel/);
assert.match(levels, /EMPLOYMENT_LEVEL_MAPPING_REQUIRED/);
assert.match(provisioning, /ANNUAL_BY_LEVEL/);
assert.match(provisioning, /\[1, 14\].*\[6, 28\]/s);
assert.match(provisioning, /newHireTreatment/);
assert.match(provisioning, /PRORATED/);
assert.match(provisioning, /BASELINE_REPROVISION/);
assert.match(provisioning, /ENTITLEMENT_DEFICIT_REVIEW_REQUIRED/);
assert.match(provisioning, /NOT_CONFIGURED_FOR_EMPLOYEE_LEVEL/);
assert.match(provisioning, /OPTIONAL_NOT_ASSIGNED/);
assert.match(provisioning, /EXPLICITLY_ASSIGNED_OR_REQUIRED/);
assert.match(provisioning, /retainedAvailable/);
assert.match(provisioning, /leaveEntitlementAllocation\.create/);
assert.match(provisioning, /leavePolicyAudit\.create/);
assert.match(provisioning, /isolationLevel: "Serializable"/);

assert.match(balance, /latestAllocation\?\.allocatedEntitlement/);
assert.match(ledger, /getEmployeePolicyBalance/);
assert.match(ledger, /status === "PENDING"/);
assert.match(ledger, /status === "APPROVED"/);
assert.match(ledger, /status === "ACTIVE"/);
assert.match(leaveRoutes, /employees\/:employeeNumber\/ledger/);
assert.match(leaveRoutes, /entitlement-matrix/);
assert.match(employeeRoutes, /provisionNewEmployeeEntitlements/);
assert.ok((employeeRoutes.match(/resolveEmploymentLevelFromDesignation/g) || []).length >= 4);
assert.match(employeeRoutes, /entitlementReconciliation:\s*"NOT_APPLIED"/);
assert.match(onboardingRoutes, /resolveEmploymentLevelFromDesignation/);
assert.match(onboardingRoutes, /Onboarding cannot be completed/);

assert.match(entitlementsPage, /Designation-driven Entitlement Matrix/);
assert.match(entitlementsPage, /Reconcile existing current-year opening entitlements/);
assert.match(requestPage, /leaveYear: String\(form\.leaveYear\)/);
assert.match(profilePanel, /Employee Leave Ledger/);
assert.match(profilePanel, /designation-derived/);
assert.match(diagnosticScript, /MANUAL_GOVERNING_POLICY_DECISION_REQUIRED/);
assert.match(diagnosticScript, /hasExistingRequestsBalancesOrHistory/);
assert.match(diagnosticScript, /DIAGNOSTIC ONLY/);
assert.match(previewScript, /Annual entitlement \/ used \/ pending \/ available/);
assert.doesNotMatch(previewScript, /retainedUsed:\s*0/);
assert.match(normalizationProposal, /a1686721-e701-4800-aa3d-d1727455fee8/);
assert.match(normalizationProposal, /ANNUAL_STD_053367/);
assert.match(normalizationProposal, /ANNUAL_SENIOR_STAFF/);
assert.match(normalizationProposal, /DRY_RUN_PREFLIGHT/);
assert.match(normalizationProposal, /STANDARD_EFFECTIVE_TO = new Date\("2026-08-22T23:59:59\.999Z"\)/);
assert.match(normalizationProposal, /effectiveTo == null \|\| new Date\(effectiveTo\) >= new Date\(effectiveFrom\)/);
assert.match(normalizationProposal, /POLICY_STATE_CHANGED_SINCE_REVIEWED_PREFLIGHT/);
assert.match(normalizationProposal, /isolationLevel: "Serializable"/);
assert.match(normalizationProposal, /leavePolicyAudit\.create/);
assert.match(normalizationProposal, /auditEventIds/);
assert.match(normalizationProposal, /beforeStates/);
assert.match(normalizationProposal, /balanceCountBefore/);
assert.match(normalizationProposal, /matrixCountAfter/);
assert.match(normalizationProposal, /governingCurrentAnnualPoliciesAfterProposedTransaction/);
assert.match(normalizationProposal, /historicalRequestsPreserved: true/);
assert.match(normalizationProposal, /entitlementRecordsChanged: 0/);
assert.doesNotMatch(normalizationProposal, /leaveRequest\.(update|delete)|leaveBalance\.(update|delete)|leaveEntitlementAllocation\.(update|delete)|leaveEntitlementAdjustment\.(update|delete)/);
assert.match(baselineReconciliation, /f50e3a3f-1153-48b6-88ba-a4ea5ef445fb/);
assert.match(baselineReconciliation, /EXACT_LEAVE_YEAR_2026_REQUIRED/);
assert.match(baselineReconciliation, /confirmationToken/);
assert.match(baselineReconciliation, /REBASE_AND_ALLOCATE/);
assert.match(baselineReconciliation, /CREATE_MISSING_ALLOCATION/);
assert.match(baselineReconciliation, /usedAmountsWillChange: 0/);
assert.match(baselineReconciliation, /pendingAmountsWillChange: 0/);
assert.match(baselineReconciliation, /affectedEmployeePolicyFingerprints/);
assert.match(baselineReconciliation, /fingerprints:\s*\{/);
assert.match(baselineReconciliation, /mode: "DRY_RUN_PREFLIGHT"/);
assert.match(baselineReconciliation, /employeeFingerprint/);
assert.match(baselineReconciliation, /policyFingerprint/);
assert.match(baselineReconciliation, /balanceFingerprint/);
assert.match(baselineReconciliation, /allocationFingerprint/);
assert.match(baselineReconciliation, /SKIPPED:/);
assert.match(baselineReconciliation, /usedValuesUnchanged: true/);
assert.match(baselineReconciliation, /optionalPoliciesUnchanged: true/);
assert.match(baselineReconciliation, /policyConflicts: preview\.summary\.conflicts/);
assert.match(baselineReconciliation, /RECONCILIATION_STATE_CHANGED_SINCE_DRY_RUN/);
assert.match(baselineReconciliation, /isolationLevel: "Serializable"/);
assert.match(baselineReconciliation, /assertPreserved/);
assert.match(baselineReconciliation, /afterById/);
assert.match(baselineReconciliation, /beforeIds/);
assert.match(baselineReconciliation, /ALLOCATION_COUNT_POSTCONDITION_FAILED/);
assert.match(baselineReconciliationPreview, /APPLY_IS_NOT_AVAILABLE_FROM_THE_DRY_RUN_COMMAND/);
assert.match(baselineReconciliationPreview, /DRY_RUN_SAFETY_ENVELOPE_INCOMPLETE/);
assert.match(baselineReconciliationPreview, /function transactionSafetyEnvelope/);
assert.match(baselineReconciliationPreview, /fingerprints: report\.fingerprints/);
assert.match(baselineReconciliationPreview, /rows: report\.rows/);
assert.match(baselineReconciliationPreview, /JSON\.stringify\(envelope/);
assert.match(baselineReconciliationPreview, /process\.stdout\.write/);
assert.match(baselineReconciliationPreview, /DRY_RUN_ASSERTION_FAILED/);
assert.doesNotMatch(baselineReconciliationPreview, /DRY RUN ONLY:/);
assert.doesNotMatch(baselineReconciliationPreview, /provisionEntitlements/);
assert.match(baselineReconciliationApply, /EXPLICIT_APPLY_FLAG_REQUIRED/);
assert.match(directory, /Employment Level/);
assert.match(directory, /employmentLevel/);
assert.match(employeeProfile, /label="Employment Level"/);
assert.match(employeeProfile, /employmentLevel/);
assert.match(onboarding, /Designation \/ Employment Level/);
assert.match(onboarding, /Employment Level required/);
assert.match(designations, /Employment Level Configuration/);
assert.match(designations, /career\/levels/);
assert.doesNotMatch(legacyLeave, /requestedUnits/);
assert.match(legacyLeave, /Navigate to="\/leave\/requests"/);
assert.doesNotMatch(staleRoutes, /import LeaveManagement/);
assert.match(staleRoutes, /Navigate to="\/leave\/requests"/);

console.log("PASS: designation-driven Employment Level and Leave Ledger contract tests passed.");
