const assert=require("assert"),fs=require("fs"),path=require("path");
const {legacyProjection,previewPolicy}=require("../src/services/leavePolicyService");
const {policyEntitlementForService}=require("../src/services/leaveService");
const schema=fs.readFileSync(path.resolve(__dirname,"../prisma/schema.prisma"),"utf8");
const service=fs.readFileSync(path.resolve(__dirname,"../src/services/leavePolicyService.js"),"utf8");
const leave=fs.readFileSync(path.resolve(__dirname,"../src/services/leaveService.js"),"utf8");
for(const model of ["LeavePolicyTemplate","LeavePolicyAudit","LeaveComplianceFloor"])assert.ok(schema.includes("model "+model));
for(const field of ["eligibilityRules","serviceBands","approvalWorkflow","lifecycleRules","payrollRules","attendanceRules","overlapRules","coverageRules"])assert.ok(schema.includes(field));
assert.ok(schema.includes("leavePolicyId  String?"),"request must reference governing policy version");
assert.ok(service.includes("organizationId"),"tenant scoping required");
assert.ok(service.includes("leavePolicyAudit.create"),"audit writes required");
assert.ok(service.includes("versionNumber: current.versionNumber + 1"),"effective-dated versions required");
assert.ok(service.includes("if (existing) return existing"),"Use Policy must be idempotent for an active tenant policy");
assert.ok(service.includes('template.code + "_CUSTOM_"'),"template clones need collision-free organization codes");
assert.ok(leave.includes("leavePolicyId:"),"request must store policy version");
assert.ok(leave.includes("request.leavePolicy?.lifecycleRules"),"lifecycle must consume policy rules");
const projected=legacyProjection({entitlementRules:{value:25,accrual:"MONTHLY"},balanceRules:{carryoverAllowed:true,maximumCarryover:10},requestRules:{minimumNotice:5}});
assert.equal(projected.entitlementDays,25);assert.equal(projected.maxCarryForwardDays,10);assert.equal(projected.noticeDays,5);
assert.equal(policyEntitlementForService({entitlementDays:20,serviceBands:[{minimumYears:0,maximumYears:2,value:20},{minimumYears:3,value:25}]},{eligibility:{measured:{serviceDays:1461}}}),25);
assert.match(previewPolicy({name:"Annual",entitlementDays:20,entitlementRules:{value:20,unit:"WORKING_DAYS",frequency:"ANNUAL"},balanceRules:{},requestRules:{},payrollRules:{treatment:"FULLY_PAID"}}),/20 working days/);
console.log("PASS: CHRIS leave policy engine tests passed.");