import fs from "node:fs";
import assert from "node:assert/strict";
const read = path => fs.readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
const request = read("src/pages/LeaveRequests.jsx");
const selector = read("src/components/leave/EmployeeSearchSelect.jsx");
const css = read("src/pages/LeaveRequests.css");
const policies = read("src/pages/LeavePolicies.jsx");
assert.match(selector, /role="listbox"/);
assert.match(selector, /role="option"/);
assert.match(selector, /department\?\.name/);
assert.match(selector, /designation\?\.name/);
assert.match(request, /request-day-calculation/);
assert.match(request, /Select active policy/);
assert.match(request, /leavePolicyId/);
assert.match(request, /Days Applied For/);
assert.match(request, /readOnly/);
assert.match(request, /Leave End Date \(inclusive\)/);
assert.doesNotMatch(request, /requestedUnits:Number|type="number".*requestedUnits/s);
assert.match(css, /max-height:calc\(100dvh - 32px\)/);
assert.match(css, /overflow-y:auto/);
assert.match(css, /position:sticky;bottom:0/);
assert.match(css, /@media\(max-width:640px\)/);
assert.match(policies, /hasPermission\("leave\.manage"\)/);
assert.match(policies, /setTimeout.*4500/s);
assert.match(policies, /alignItems:"flex-start"/);
console.log("PASS: leave request addendum frontend tests passed.");
