/* eslint-disable react-refresh/only-export-components */
import { useNavigate } from "react-router-dom";
export const LEAVE_STATUS={DRAFT:{label:"Draft",color:"#94A3B8",bg:"rgba(148,163,184,.12)"},PENDING:{label:"Pending",color:"#FBBF24",bg:"rgba(251,191,36,.12)"},APPROVED:{label:"Approved",color:"#D4AF37",bg:"rgba(212,175,55,.12)"},ACTIVE:{label:"Active",color:"#5EEAD4",bg:"rgba(45,212,191,.12)"},COMPLETED:{label:"Completed",color:"#86EFAC",bg:"rgba(34,197,94,.12)"},REJECTED:{label:"Rejected",color:"#FCA5A5",bg:"rgba(239,68,68,.12)"},CANCELLED:{label:"Cancelled",color:"#FDA4AF",bg:"rgba(127,29,29,.16)"}};
export function LeavePage({title,description,actions,children}){const nav=useNavigate();return <div style={{color:"var(--chris-text-main)"}}><button style={styles.back} onClick={()=>nav("/leave")}>{"\u2190"} Leave Overview</button><header style={styles.header}><div><b style={styles.eye}>LEAVE OPERATIONS</b><h1 style={{margin:"7px 0 5px"}}>{title}</h1><p style={styles.muted}>{description}</p></div>{actions&&<div style={styles.actions}>{actions}</div>}</header>{children}</div>}
export function Panel({title,subtitle,children,style}){return <section style={{...styles.panel,...style}}>{title&&<><h2 style={{margin:"0 0 5px"}}>{title}</h2>{subtitle&&<p style={styles.muted}>{subtitle}</p>}</>}{children}</section>}
export function Notice({children,error}){return <div role={error?"alert":"status"} style={{...styles.notice,color:error?"#FCA5A5":"var(--chris-success)"}}>{children}</div>}
export function Empty({children}){return <div style={styles.empty}>{children}</div>}
export function StatusBadge({status}){const item=LEAVE_STATUS[status]||{label:status||"Unknown",color:"#CBD5E1",bg:"rgba(255,255,255,.08)"};return <span style={{display:"inline-block",padding:"5px 8px",borderRadius:999,fontSize:11,fontWeight:900,color:item.color,background:item.bg}}>{item.label}</span>}
export function Table({columns,rows,empty}){if(!rows.length)return <Empty>{empty}</Empty>;return <div style={styles.tableWrap}><table style={styles.table}><thead><tr>{columns.map(c=><th key={c.key} style={styles.th}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{columns.map(c=><td key={c.key} style={styles.td}>{c.render?c.render(row):row[c.key]??"-"}</td>)}</tr>)}</tbody></table></div>}
export const formatDate=v=>v?new Date(v).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"-";
export const employeeName=e=>[e?.firstName,e?.middleName,e?.lastName].filter(Boolean).join(" ");
export const daysRemaining=end=>Math.max(0,Math.ceil((new Date(end)-new Date())/86400000));
export const styles={panel:{background:"linear-gradient(145deg,rgba(12,38,26,.92),rgba(7,18,13,.97))",border:"1px solid var(--chris-border-gold)",borderRadius:"var(--chris-radius-card)",padding:20,boxShadow:"var(--chris-shadow-card)",marginBottom:18},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,marginBottom:22},eye:{color:"var(--chris-gold)",fontSize:11,letterSpacing:".14em"},muted:{margin:"4px 0",color:"var(--chris-text-secondary)",fontSize:13,lineHeight:1.5},back:{border:0,background:"transparent",color:"var(--chris-gold)",padding:"0 0 16px",fontWeight:800},actions:{display:"flex",gap:8,flexWrap:"wrap"},primary:{border:0,borderRadius:9,padding:"10px 13px",background:"linear-gradient(135deg,var(--chris-gold),var(--chris-gold-deep))",color:"#07110C",fontWeight:800},button:{border:"1px solid var(--chris-border-soft)",borderRadius:9,padding:"9px 12px",background:"rgba(255,255,255,.04)",color:"var(--chris-text-main)",fontWeight:700},input:{padding:"10px 11px",borderRadius:8,border:"1px solid var(--chris-border-soft)",background:"var(--chris-input-bg)",color:"var(--chris-text-main)"},notice:{padding:"12px 15px",border:"1px solid var(--chris-border-soft)",borderRadius:10,background:"rgba(255,255,255,.035)",marginBottom:16},empty:{padding:"25px 8px",color:"var(--chris-text-secondary)",textAlign:"center"},tableWrap:{overflowX:"auto",marginTop:14},table:{width:"100%",borderCollapse:"collapse",minWidth:850},th:{padding:"11px 10px",textAlign:"left",fontSize:11,color:"var(--chris-gold)",borderBottom:"1px solid var(--chris-border-soft)",whiteSpace:"nowrap"},td:{padding:"12px 10px",fontSize:13,color:"var(--chris-text-main)",borderBottom:"1px solid rgba(255,255,255,.055)",verticalAlign:"top"}};