import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../services/api";

const card = { background:"var(--chris-dashboard-surface,#fff)", border:"1px solid var(--chris-dashboard-border,#ddd)", borderRadius:14, padding:18 };
const button = { border:0, borderRadius:10, padding:"10px 14px", fontWeight:800, cursor:"pointer" };

export default function CHRiSAutomationCentre({ mode="all" }) {
  const [notes,setNotes]=useState([]); const [employees,setEmployees]=useState([]); const [kpis,setKpis]=useState([]);
  const [settings,setSettings]=useState(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const [note,setNote]=useState({category:"OTHER",employeeId:"",originalNote:""});
  const [selectedEmployee,setSelectedEmployee]=useState(""); const [generating,setGenerating]=useState(false);

  const load=async()=>{
    setLoading(true);
    try{
      const calls=[
        apiRequest("/api/chris-automation/settings").catch(()=>null),
        apiRequest("/api/chris-automation/payroll-notes").catch(()=>({data:[]})),
        apiRequest("/api/chris-automation/performance/employees").catch(()=>({data:[]})),
        apiRequest("/api/chris-automation/performance/kpis").catch(()=>({data:[]})),
      ];
      const [s,n,e,k]=await Promise.all(calls);
      setSettings(s?.data||null); setNotes(n?.data||[]); setEmployees(e?.data||[]); setKpis(k?.data||[]);
    } finally { setLoading(false); }
  };
  useEffect(()=>{load()},[]);
  const currentEmployee=useMemo(()=>employees.find(e=>e.id===selectedEmployee),[employees,selectedEmployee]);

  const submitNote=async(e)=>{
    e.preventDefault(); setMessage("");
    try{await apiRequest("/api/chris-automation/payroll-notes",{method:"POST",body:note}); setNote({category:"OTHER",employeeId:"",originalNote:""}); setMessage("Payroll note submitted to Head HR and Head of Audit & Internal Control."); await load();}
    catch(err){setMessage(err.message)}
  };
  const review=async(id,status)=>{
    try{await apiRequest(`/api/chris-automation/payroll-notes/${id}/review`,{method:"PATCH",body:{status,reviewedNote:"Reviewed in CHRiS"}}); await load();}
    catch(err){setMessage(err.message)}
  };
  const generate=async()=>{
    if(!selectedEmployee)return;
    setGenerating(true);setMessage("");
    try{const r=await apiRequest("/api/chris-automation/performance/kpis/generate",{method:"POST",body:{employeeId:selectedEmployee}});setMessage(`KPIs generated by ${r.data?.source||"Performance AI Agent"}.`);await load();}
    catch(err){setMessage(err.message)}
    finally{setGenerating(false)}
  };
  const approve=async(id)=>{try{await apiRequest(`/api/chris-automation/performance/kpis/${id}/approve`,{method:"PATCH",body:{}});await load()}catch(err){setMessage(err.message)}};

  return <div style={{maxWidth:1400,margin:"0 auto",padding:"24px 18px",display:"grid",gap:18}}>
    <header>
      <div style={{fontSize:12,fontWeight:900,letterSpacing:1.2,opacity:.7}}>CHRiS AUTOMATION</div>
      <h1 style={{margin:"5px 0"}}>Payroll & Performance Control Centre</h1>
      <p style={{margin:0,opacity:.75}}>Branch payroll notes, dual Head Office visibility, AI-assisted KPI setting and quarterly performance controls.</p>
    </header>
    {message&&<div style={{...card,borderColor:"#D4AF37"}}>{message}</div>}

    {(mode==="all"||mode==="payroll")&&<section style={{display:"grid",gap:16}}>
      <div style={{...card,display:"grid",gap:12}}>
        <h2 style={{margin:0}}>Branch Payroll Notes & Updates</h2>
        <p style={{margin:0,opacity:.72}}>Every submission is routed to both the Head HR Payroll Inbox and Head of Audit & Internal Control Payroll Inbox. Original notes are preserved.</p>
        <form onSubmit={submitNote} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
          <select value={note.employeeId} onChange={e=>setNote({...note,employeeId:e.target.value})} style={{padding:11,borderRadius:9,border:"1px solid #ccc"}}><option value="">Employee (optional)</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeNumber} — {e.employeeName}</option>)}</select>
          <select value={note.category} onChange={e=>setNote({...note,category:e.target.value})} style={{padding:11,borderRadius:9,border:"1px solid #ccc"}}>{["SALARY_CHANGE","ALLOWANCE","DEDUCTION","OVERTIME","ABSENCE","LEAVE","TRANSFER","EXIT","OTHER"].map(x=><option key={x}>{x}</option>)}</select>
          <textarea required value={note.originalNote} onChange={e=>setNote({...note,originalNote:e.target.value})} placeholder="Enter payroll-impacting note/update…" style={{gridColumn:"1/-1",minHeight:100,padding:12,borderRadius:9,border:"1px solid #ccc"}}/>
          <button style={{...button,background:"#D4AF37",gridColumn:"1/-1"}}>Submit Payroll Update</button>
        </form>
      </div>
      <div style={card}>
        <h3 style={{marginTop:0}}>Payroll Notes Inbox</h3>
        <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Employee</th><th align="left">Category</th><th align="left">Original Note</th><th align="left">Status</th><th></th></tr></thead><tbody>{notes.map(n=><tr key={n.id} style={{borderTop:"1px solid #eee"}}><td>{n.employeeNumber||"—"}<br/><small>{n.employeeName||""}</small></td><td>{n.category}</td><td>{n.originalNote}</td><td>{n.status}</td><td style={{whiteSpace:"nowrap"}}>{n.status!=="APPROVED"&&n.status!=="IMPLEMENTED"&&<button onClick={()=>review(n.id,"APPROVED")} style={{...button,background:"#1f7a4d",color:"#fff",marginRight:6}}>Approve</button>}{n.status!=="IMPLEMENTED"&&<button onClick={()=>review(n.id,"IMPLEMENTED")} style={{...button,background:"#333",color:"#fff"}}>Implemented</button>}</td></tr>)}</tbody></table></div>
      </div>
    </section>}

    {(mode==="all"||mode==="performance")&&<section style={{display:"grid",gap:16}}>
      <div style={{...card,display:"grid",gap:12}}>
        <h2 style={{margin:0}}>Performance Evaluation AI Agent</h2>
        <p style={{margin:0,opacity:.72}}>Generate role-specific quarterly KPIs and objective goals. HR and line management approve before publication to ESS.</p>
        <div style={{display:"flex",gap:10,flexWrap:"wrap"}}><select value={selectedEmployee} onChange={e=>setSelectedEmployee(e.target.value)} style={{minWidth:320,padding:11,borderRadius:9,border:"1px solid #ccc"}}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeNumber} — {e.employeeName} — {e.designation||"No designation"}</option>)}</select><button disabled={!selectedEmployee||generating} onClick={generate} style={{...button,background:"#D4AF37"}}>{generating?"Generating…":"Set KPIs with AI Agent"}</button></div>
        {currentEmployee&&<div style={{fontSize:13,opacity:.7}}>Role: <b>{currentEmployee.designation||"Not mapped"}</b> · Department: <b>{currentEmployee.department||"Not mapped"}</b></div>}
      </div>
      <div style={card}>
        <h3 style={{marginTop:0}}>KPI Approval Queue</h3>
        <div style={{display:"grid",gap:10}}>{kpis.map(k=><div key={k.id} style={{border:"1px solid #eee",borderRadius:12,padding:14,display:"grid",gap:5}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>{k.employeeName} — {k.title}</b><span>{k.status}</span></div><div>{k.objective}</div><small>{k.measurement} · Target: {k.target} · Weight: {k.weight}% · Source: {k.source}</small>{k.status!=="APPROVED"&&<button onClick={()=>approve(k.id)} style={{...button,background:"#1f7a4d",color:"#fff",justifySelf:"start"}}>Approve KPI</button>}</div>)}</div>
      </div>
    </section>}

    <section style={card}>
      <h2 style={{marginTop:0}}>Employee Self-Service</h2>
      <p style={{marginBottom:8}}>Dedicated ESS entry point for employee-facing workflows.</p>
      <a href="/ess" style={{fontWeight:900}}>Open ESS Portal →</a>
      <div style={{marginTop:10,fontSize:13,opacity:.7}}>Configured ESS URL: {settings?.essUrl||"/ess"}</div>
      <div style={{marginTop:12,fontSize:13}}>Birthday and employment-anniversary automation is configured to identify the sender as <b>Zermatt Liquor Limited</b> with <b>Powered by CHRiS</b> in the footer.</div>
    </section>
  </div>
}
