import { useCallback, useEffect, useRef, useState } from "react";
import { LeavePage, Notice, Panel, StatusBadge, Table, employeeName, formatDate, styles } from "../components/leave/LeaveUi";
import useAuthorization from "../hooks/useAuthorization";
import { apiRequest } from "../services/api";
import "./LeaveExceptions.css";

const today = () => new Date().toISOString().slice(0, 10);
const initialForm = { mode: "INVESTIGATE", note: "", newStatus: "ACTIVE", reason: "", leavePolicyId: "", leaveTypeId: "", startDate: "", endDate: "", actualReturnDate: "", status: "ACTIVE", returnStatus: "ACTIVE" };

export default function LeaveExceptions() {
  const { hasPermission } = useAuthorization(), canManage = hasPermission("leave.manage");
  const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(initialForm),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const timer=useRef(null),reviewPanelRef=useRef(null);
  const load=useCallback(async()=>{try{const response=await apiRequest("/api/leave/exceptions");setRows(response.data||[]);setError("");return response.data||[]}catch(requestError){setError(requestError.message||"Unable to load Leave Exceptions.");return[]}},[]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[]);
  useEffect(()=>{if(!selected)return undefined;const frame=window.requestAnimationFrame(()=>{const panel=reviewPanelRef.current;if(!panel)return;const safeTop=Number.parseFloat(window.getComputedStyle(document.documentElement).getPropertyValue("--chris-operational-panel-safe-top"))||90;const bounds=panel.getBoundingClientRect();if(bounds.top<safeTop||bounds.bottom>window.innerHeight-12)panel.scrollIntoView({behavior:"smooth",block:"nearest"})});return()=>window.cancelAnimationFrame(frame)},[selected]);
  function review(row){if(timer.current)window.clearTimeout(timer.current);setMessage("");setError("");setSelected(row);setForm(initialForm)}
  function showSuccess(text,closeAfter=false){setError("");setMessage(text);if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>{setMessage("");if(closeAfter)setSelected(null);timer.current=null},4500)}
  async function submit(event){event.preventDefault();if(!selected||!canManage)return;setSaving(true);setError("");setMessage("");const number=encodeURIComponent(selected.employee.employeeNumber);try{if(form.mode==="INVESTIGATE"){await apiRequest(`/api/leave/exceptions/${number}/investigation`,{method:"POST",body:{note:form.note}});const refreshed=await load();setSelected(refreshed.find(row=>row.employee.employeeNumber===selected.employee.employeeNumber)||selected);showSuccess("Investigation note recorded. The exception remains open.")}else if(form.mode==="RESTORE"){await apiRequest(`/api/leave/exceptions/${number}/restore-status`,{method:"POST",body:{newStatus:form.newStatus,reason:form.reason}});await load();showSuccess("Employee working status restored. Protected leave balances and history were unchanged.",true)}else{await apiRequest(`/api/leave/exceptions/${number}/reconstruct`,{method:"POST",body:form});await load();showSuccess("Administrative historical leave record reconstructed without a second balance deduction.",true)}}catch(requestError){setError(requestError.message||"Unable to resolve Leave Exception.")}finally{setSaving(false)}}
  const columns=[{key:"employee",label:"Employee",render:row=>`${employeeName(row.employee)} (${row.employee.employeeNumber})`},{key:"mismatch",label:"Mismatch"},{key:"employeeStatus",label:"Employee Status",render:row=><StatusBadge status={row.employee.status}/>},{key:"requestStatus",label:"Request Status",render:row=><StatusBadge status={row.activeRequestStatus}/>},{key:"detectedAt",label:"Detected",render:row=>formatDate(row.detectedAt)},{key:"resolutionStatus",label:"Resolution Status",render:row=><StatusBadge status={row.resolutionStatus}/>},{key:"action",label:"Action",render:row=><button type="button" style={styles.button} onClick={()=>review(row)}>Review Exception</button>}];
  return <LeavePage title="Leave Exceptions" description="Controlled HR review of authoritative employee-status and leave-lifecycle mismatches.">{error&&!selected&&<Notice error>{error}</Notice>}<Panel><Table rows={rows} columns={columns} empty="No leave consistency exceptions detected."/></Panel>{selected&&<div className="chris-operational-panel-overlay" style={overlay} role="dialog" aria-modal="true" aria-label="Review Leave Exception"><form ref={reviewPanelRef} className="chris-operational-panel" onSubmit={submit} style={modal}><div style={modalHeader}><div><div style={eyebrow}>LEAVE EXCEPTION CONTROL</div><h2 style={{margin:"4px 0"}}>Review Exception</h2><p style={muted}>{selected.mismatch}</p></div><button type="button" style={styles.button} onClick={()=>setSelected(null)}>Close</button></div>{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<ExceptionContext exception={selected}/>{selected.latestInvestigation&&<Notice>Latest investigation: {selected.latestInvestigation.note} · {formatDate(selected.latestInvestigation.createdAt)}</Notice>}<div style={modeTabs}>{[["INVESTIGATE","Keep Open"],["RESTORE","Restore Working Status"],["RECONSTRUCT","Reconstruct Historical Leave"]].map(([value,label])=><button type="button" key={value} style={form.mode===value?styles.primary:styles.button} onClick={()=>{setError("");setMessage("");setForm({...initialForm,mode:value})}}>{label}</button>)}</div>{form.mode==="INVESTIGATE"&&<label style={field}>Investigation note<textarea style={textarea} value={form.note} onChange={event=>setForm({...form,note:event.target.value})} required/></label>}{form.mode==="RESTORE"&&<div style={formGrid}><label style={field}>Correct working status<select style={styles.input} value={form.newStatus} onChange={event=>setForm({...form,newStatus:event.target.value})}><option value="ACTIVE">Active</option><option value="PROBATION">Probation</option></select></label><label style={field}>Resolution reason<textarea style={textarea} value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})} required/></label></div>}{form.mode==="RECONSTRUCT"&&<ReconstructionFields form={form} setForm={setForm} policies={selected.policies}/>}<div style={actions}><button type="button" style={styles.button} onClick={()=>setSelected(null)}>Cancel</button><button type="submit" style={styles.primary} disabled={saving||!canManage}>{saving?"Saving...":form.mode==="INVESTIGATE"?"Record Investigation Note":form.mode==="RESTORE"?"Restore Status":"Reconstruct Leave History"}</button></div>{!canManage&&<Notice error>leave.manage permission is required to resolve or reconstruct a Leave Exception.</Notice>}</form></div>}</LeavePage>;
}

function ExceptionContext({exception}){const facts=[["Employee Number",exception.employee.employeeNumber],["Employee Name",employeeName(exception.employee)],["Department",exception.employee.department?.name||"—"],["Designation",exception.employee.designation?.name||"—"],["Employment Level",exception.employee.employmentLevel?.name||"—"],["Employee Status",exception.employee.status],["Active Request",exception.activeRequestStatus],["Leave Year",exception.leaveYear],["Detected",formatDate(exception.detectedAt)]];return <><section style={contextGrid}>{facts.map(([label,value])=><div key={label} style={contextItem}><span style={muted}>{label}</span><strong>{value}</strong></div>)}</section><section><h3>Relevant balances and policies</h3><div style={balanceGrid}>{exception.balances.map(balance=><article key={balance.id} style={balanceCard}><strong>{balance.leaveType?.name}</strong><span>Entitlement: {balance.entitlement}</span><span>Used: {balance.used}</span><span>Pending: {balance.committed}</span><span>Available: {balance.available}</span></article>)}</div></section></>}
function ReconstructionFields({form,setForm,policies}){const choosePolicy=id=>{const policy=policies.find(item=>item.id===id);setForm({...form,leavePolicyId:id,leaveTypeId:policy?.leaveTypeId||""})};return <div style={formGrid}><label style={field}>Leave Policy<select style={styles.input} value={form.leavePolicyId} onChange={event=>choosePolicy(event.target.value)} required><option value="">Select governing policy family</option>{policies.map(policy=><option key={policy.id} value={policy.id}>{policy.leaveType?.name} · {policy.name} v{policy.versionNumber}</option>)}</select></label><label style={field}>Leave Type<input style={styles.input} value={policies.find(policy=>policy.id===form.leavePolicyId)?.leaveType?.name||""} readOnly/></label><label style={field}>Start Date<input style={styles.input} type="date" value={form.startDate} max={today()} onChange={event=>setForm({...form,startDate:event.target.value})} required/></label><label style={field}>Expected Return Date<input style={styles.input} type="date" value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})} required/></label><label style={field}>Lifecycle Status<select style={styles.input} value={form.status} onChange={event=>setForm({...form,status:event.target.value,actualReturnDate:event.target.value==="ACTIVE"?"":form.actualReturnDate})}><option value="ACTIVE">Active — currently on leave</option><option value="COMPLETED">Completed — already returned</option></select></label>{form.status==="COMPLETED"&&<label style={field}>Actual Return Date<input style={styles.input} type="date" value={form.actualReturnDate} onChange={event=>setForm({...form,actualReturnDate:event.target.value})} required/></label>}<label style={field}>{form.status==="COMPLETED"?"Return-to-Work Status":"Pre-leave Working Status"}<select style={styles.input} value={form.returnStatus} onChange={event=>setForm({...form,returnStatus:event.target.value})} required><option value="ACTIVE">Active</option><option value="PROBATION">Probation</option></select></label><label style={{...field,gridColumn:"1/-1"}}>Historical reconstruction reason / notes<textarea style={textarea} value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})} required/></label></div>}

const overlay={position:"fixed",zIndex:1200,display:"grid",placeItems:"center",background:"rgba(0,8,5,.78)",backdropFilter:"blur(5px)"},modal={width:"min(980px,96vw)",overflowY:"auto",padding:22,border:"1px solid rgba(212,175,55,.65)",borderRadius:18,background:"#041c13",color:"#f7faf8",boxShadow:"0 28px 70px rgba(0,0,0,.55)"},modalHeader={display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start"},eyebrow={color:"#d4af37",fontSize:10,fontWeight:900,letterSpacing:".14em"},muted={margin:0,color:"#adc0b5",fontSize:12},contextGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8,margin:"16px 0"},contextItem={display:"grid",gap:4,padding:10,border:"1px solid rgba(255,255,255,.09)",borderRadius:9,background:"rgba(255,255,255,.025)"},balanceGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:9},balanceCard={display:"grid",gap:4,padding:11,border:"1px solid rgba(212,175,55,.25)",borderRadius:10,background:"#061a11"},modeTabs={display:"flex",gap:8,flexWrap:"wrap",margin:"18px 0 14px"},formGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12},field={display:"grid",gap:6,color:"#bdcbc3",fontSize:12,fontWeight:800},textarea={...styles.input,minHeight:76,padding:10,resize:"vertical"},actions={display:"flex",justifyContent:"flex-end",gap:9,marginTop:18,flexWrap:"wrap"};
