/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import {apiRequest} from "../services/api";
import useAuthorization from "../hooks/useAuthorization";
import {LeavePage,Panel,Notice,Table,StatusBadge,formatDate,employeeName,styles} from "../components/leave/LeaveUi";
import {returnQueue} from "../components/leave/leaveSelectors";
export default function LeaveReturns(){const {hasPermission,loading:permissionLoading}=useAuthorization(),canEdit=hasPermission("leave.manage"),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[dates,setDates]=useState({});
async function load(){setLoading(true);setError("");try{const response=await apiRequest("/api/leave/requests?status=ACTIVE");setRows(returnQueue(Array.isArray(response?.data)?response.data:[]))}catch(e){setError(e.message||"Unable to load return-to-work cases.");setRows([])}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function submit(request){setError("");try{await apiRequest(`/api/leave/requests/${request.id}/return`,{method:"POST",body:JSON.stringify({returnDate:dates[request.id]||new Date().toISOString().slice(0,10)})});setMessage(`${employeeName(request.employee)} returned to work.`);await load()}catch(e){setError(e.message||"Unable to complete return to work.")}}
const columns=[{key:"employee",label:"Employee",render:r=>`${employeeName(r.employee)} (${r.employee?.employeeNumber})`},{key:"type",label:"Leave Type",render:r=>r.leaveType?.name},{key:"status",label:"Status",render:r=><StatusBadge status={r.status}/>},{key:"expected",label:"Expected Return",render:r=>formatDate(r.endDate)},{key:"actual",label:"Actual Return",render:r=><input style={styles.input} type="date" value={dates[r.id]||new Date().toISOString().slice(0,10)} onChange={e=>setDates({...dates,[r.id]:e.target.value})}/>},{key:"rules",label:"Return Requirements",render:r=>r.leavePolicy?.lifecycleRules?.returnDocumentationRequired?"Documentation required":r.leavePolicy?.lifecycleRules?.fitnessCertificateRequired?"Fitness-to-work required":"No additional requirement"},{key:"action",label:"Action",render:r=><button disabled={!canEdit} style={{...styles.primary,opacity:canEdit?1:.5}} onClick={()=>submit(r)}>Confirm Return</button>}];
return <LeavePage title="Return to Work" description="Process employees from active leave back to active employment.">{!permissionLoading&&!canEdit&&<Notice error>Read-only access: leave.manage is required to confirm a return.</Notice>}{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}<Panel title="Return Queue" subtitle="Only ACTIVE requests appear. The queue refreshes immediately after confirmation.">{loading?<div style={styles.empty}>Loading return-to-work cases...</div>:<Table rows={rows} columns={columns} empty="No employees are currently awaiting return-to-work processing."/>}</Panel></LeavePage>}